version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: expensetrackerdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: trackerExpenses!
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
    driver: local
